- README.md
> docs: grammar and spelling

- README.md
- admin/README.md
After updating the [hoodie-client README](https://github.com/hoodiehq/hoodie-client),
I want to normalise all the others by following the same structure. I hope it
makes all sense?
ping @hipsterbrown
> README update

- admin/index.js
- index.js
- lib/username.js
- tests/specs/admin/constructor-test.js
- tests/specs/constructor-test.js
- tests/specs/index.js
- tests/specs/username-test.js
> account.username & admin.username

- README.md
- tests/fixtures/put-session-401.json
- tests/integration/api-test.js
- tests/integration/index.js
- utils/request.js
> handle 4xx errors

- README.md
- lib/sign-in.js
- lib/sign-up.js
- test/integration/events-test.js
- test/unit/sign-in-test.js
> Emit 'reauthenticate' instead of 'signin' when unauthenticated

- README.md
- index.js
- lib/destroy.js
- test/integration/destroy-test.js
- test/unit/destroy-test.js
Implemented account.destroy() as described in issue #53 
closes #53
> account.destroy

- README.md
- lib/update.js
- test/integration/events-test.js
- test/unit/update-test.js
> "update" event

- test/integration/fetch-url-test.js
- test/unit/fetch-test.js
- test/unit/profile-fetch-test.js
> WIP use `state.url` instead of `state.baseUrl`

- README.md
- index.js
- lib/fetch.js
- lib/has-invalid-session.js
- lib/profile-fetch.js
- lib/profile-update.js
- lib/update.js
- test/integration/constructor-test.js
- test/integration/fetch-url-test.js
- test/integration/unauthenticate-test.js
- test/unit/has-invalid-session.js
- test/unit/profile-update-test.js
closes #54
closes #56 
closes #64
> WIP issue 56 add is-unauthenticated and unauthenticated event

- README.md
> fix a bug of  example account.profile.fetch() in  README

- README.md
- admin/README.md
- admin/index.js
- lib/sign-in.js
- lib/sign-out.js
- lib/sign-up.js
- package.json
> Rename module and repo

- admin/index.js
- index.js
Fixes https://github.com/hoodiehq/hoodie-account-client/issues/83
> #83: Bind null in object constructor

- README.md
> docs(README): setup instructions

- lib/update.js
- test/unit/update-test.js
> account.update: set session ID from `x-set-session` response header

- test/integration/sign-out-test.js
https://github.com/hoodiehq/camp/issues/9
> test for signout event timing bug

- lib/sign-out.js
- test/integration/sign-out-test.js
> hoodie.account.isSignedIn() returns true in “signout" event handler

- index.js
- test/integration/fetch-url-test.js
see hoodiehq/hoodie-account#37 & hoodiehq/hoodie-account#39
> account.fetch() and account.profile.fetch() fixies

- lib/profile-update.js
- test/fixtures/update-profile.json
- test/integration/update-profile-test.js
see hoodiehq/hoodie-account#38
> account.profile.update() bug

- README.md
I added instructions on how to test hoodie-account-client in a browser to the README.
> docs: Described procedure to test in browser

- lib/profile-fetch.js
- test/unit/profile-fetch-test.js
> hoodie.account.fetch() does not store response in localStorage

- test/integration/constructor-test.js
- utils/get-state.js
> new Account(url)

- admin/index.js
- lib/destroy.js
- lib/fetch.js
- lib/id.js
- lib/profile-fetch.js
- lib/profile-update.js
- lib/sign-in.js
- lib/sign-out.js
- lib/update.js
- test/unit/destroy-test.js
- test/unit/profile-fetch-test.js
- test/unit/profile-update-test.js
- test/unit/sign-in-test.js
- test/unit/sign-out-test.js
- test/unit/update-test.js
- utils/clear-session.js
- utils/get-account.js
- utils/get-state.js
- utils/localstorage-store.js
- utils/save-account.js
No changes, just a refactoring in preparation of #127
> refactor store

- lib/sign-in.js
- test/unit/sign-in-test.js
> account.signIn({token})

- lib/profile-get.js
- test/unit/profile-get-test.js
> account.profile.get(unknown)` returns `undefined` not `{}`
